name: Go

on: pull_request

defaults:
  run:
    working-directory: ./go

jobs:
  test:
    runs-on: ubuntu-latest

    outputs:
      result: ${{ steps.test.outputs.result }}

    steps:
    - uses: actions/checkout@v2
    - run: git status
    - run: git log

    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.7

    - run: go build -v ./...

    - id: test
      run: |
        result=$(go test ./...)
        echo $result
        echo "::set-output name=result::$result"

  comment:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            if (context.issue.number) {
              await github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: "${{needs.test.outputs.result}}"
              })
            } else {
              console.log('Skipped')
            }
