name: Go

on: pull_request

defaults:
  run:
    working-directory: ./go

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: git status
    - run: git log

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.7

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
